### ISSUE TITLE
App crashes when cancel button is press

### ISSUE THREAD

**Issue by AgustinV08** [skhye05/nativescript-multi-select#12]
The app crashes when i trigger the onCancel event of the plugin

**Comment by andthereitgoes** [comment]
@AgustinV08 I am having the same issue as well. Were you able to fix your issue?

**Comment by mwood77** [comment]
I've created a very quick/dirty fix. You can use this PR to see the existing code that is causing you issue, and fix it if needed (assuming this PR won't get merged).
