### ISSUE TITLE
ERROR TypeError: com.abdeveloper.library.MultiSelectModel is not a constructor

### ISSUE THREAD

**Issue by jabrware** [skhye05/nativescript-multi-select#5]
### Which platform(s) does your issue occur on?
- Android
- Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.4
- Cross-platform modules: 5.2.2
- Runtime(s): 5.2.1
- Plugin(s): 
 "dependencies": {
    "@angular/animations": "^7.2.10",
    "@angular/common": "^7.2.10",
    "@angular/compiler": "^7.2.10",
    "@angular/core": "^7.2.10",
    "@angular/forms": "^7.2.10",
    "@angular/http": "^7.2.10",
    "@angular/platform-browser": "^7.2.10",
    "@angular/platform-browser-dynamic": "^7.2.10",
    "@angular/router": "^7.2.10",
    "@ngx-translate/core": "^11.0.1",
    "base-64": "^0.1.0",
    "nativescript-angular": "^7.2.3",
    "nativescript-cardview": "^3.1.1",
    "nativescript-floatingactionbutton": "^5.0.3",
    "nativescript-multi-select": "^1.0.6",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-ngx-shadow": "^6.4.0",
    "nativescript-picker": "^1.0.1",
    "nativescript-plugin-firebase": "^8.0.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-listview": "^6.0.0",
    "nativescript-ui-sidedrawer": "^6.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.4.0",
    "tns-core-modules": "^5.2.2",
    "utf8": "^3.0.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^7.2.10",
    "@nativescript/schematics": "^0.5.2",
    "@ngtools/webpack": "^7.3.6",
    "@types/base-64": "^0.1.3",
    "@types/utf8": "^2.1.6",
    "nativescript-dev-sass": "^1.7.0",
    "nativescript-dev-typescript": "^0.9.0",
    "nativescript-dev-webpack": "^0.20.3",
    "node-sass": "^4.11.0",
    "tns-platform-declarations": "^5.2.2"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Running the same ng-demo

**Comment by skhye05** [comment]
Hi, did you try to clean up your platform by running `tns platform clean android` and try to build again?

**Comment by jabrware** [comment]
Yes I tried it.

**Comment by jabrware** [comment]
It works after updating android platform version

**Comment by rafaelcmrj** [comment]
@ashraf-jabr did you update to which version? I'm having the same issue

**Comment by jabrware** [comment]
@rafaelcmrj , this my versions now and they works:

```json
"nativescript-multi-select": "^1.0.6"
"tns-core-modules": "^5.3.1"
"nativescript-angular": "^7.2.3"
```

also try to clean platform using 
```
tns platform remove android
tns platform add android
```

**Comment by rafaelcmrj** [comment]
@ashraf-jabr thank you! it worked!
